using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

public static class MapEditorExportSmokeTest
{
    [MenuItem("Tools/MapEditor/Run Export Smoke Test")]
    public static void RunFromMenu()
    {
        Run();
    }

    public static void RunBatchMode()
    {
        if (!Run())
        {
            throw new InvalidOperationException("MapEditor export smoke test failed.");
        }
    }

    public static bool Run()
    {
        string root = Path.Combine(Path.GetTempPath(), "MapEditorExportSmokeTest_" + DateTime.Now.ToString("yyyyMMdd_HHmmss"));
        Directory.CreateDirectory(root);

        string sourceTilesetPath = CreateSmokeTestTileset(root);
        MapData mapData = CreateSmokeTestMap(sourceTilesetPath);
        MapEditorSpawnPointData[] spawnPoints =
        {
            new MapEditorSpawnPointData("SpawnPoint_1", 1, 1, "Any"),
            new MapEditorSpawnPointData("SpawnPoint_2", 2, 1, "Any")
        };

        PixelChromaMapValidationReport validation = MapEditorPixelChromaValidationService.Validate(mapData, 1, 1, spawnPoints);

        if (!validation.isValid)
        {
            MapEditorPixelChromaValidationService.Log(validation);
            Debug.LogError("MapEditor export smoke test failed during validation.");
            return false;
        }

        ValidateValidationReport(validation);
        ValidateLayerRoundTrip(mapData);

        string mapPath = Path.Combine(root, "map.json");
        MapEditorPixelChromaExportService mapExport = new MapEditorPixelChromaExportService();

        if (!mapExport.Export(mapData, mapPath, "smoke_test", 16, 1, 1, spawnPoints))
        {
            Debug.LogError("MapEditor export smoke test failed while writing map.json.");
            return false;
        }

        if (!ValidateMapJson(mapPath))
        {
            return false;
        }

        string packagePath = Path.Combine(root, "workshop_package");
        MapEditorWorkshopExportService workshopExport = new MapEditorWorkshopExportService((_, _) => null);

        if (!workshopExport.Export(
            mapData,
            packagePath,
            "smoke_test",
            "Smoke Test",
            "MapEditor",
            "Generated by MapEditor export smoke test.",
            "1.0.0",
            "Private",
            "Map,SmokeTest",
            1,
            1,
            spawnPoints,
            16,
            false))
        {
            Debug.LogError("MapEditor export smoke test failed while writing workshop package.");
            return false;
        }

        if (!ValidateWorkshopPackage(packagePath))
        {
            return false;
        }

        Debug.Log("MapEditor export smoke test passed: " + root);
        return true;
    }

    [MenuItem("Tools/MapEditor/Run PNG Overwrite Smoke Test")]
    public static void RunPngOverwriteTest()
    {
        Texture2D texture = null;
        Sprite sprite = null;
        GameObject cellObject = null;

        try
        {
            texture = CreatePngOverwriteSourceTexture();
            sprite = Sprite.Create(texture, new Rect(0, 0, 16, 16), new Vector2(0.5f, 0.5f), 16f);
            cellObject = new GameObject("PngOverwriteSmokeCell", typeof(RectTransform), typeof(Image));
            GridCell cell = cellObject.AddComponent<GridCell>();

            MapData mapData = new MapData(1, 1);
            mapData.SetTileOnLayer(0, 0, MapEditorLayerType.Ground, MapEditorManager.CustomImageTileId, Color.white, "smoke.png", 0, 0, false, false);

            Dictionary<Vector2Int, GridCell> cells = new Dictionary<Vector2Int, GridCell>();
            MapEditorMapEditingService editing = new MapEditorMapEditingService(
                () => mapData,
                () => MapEditorLayerType.Ground,
                _ => true,
                cells,
                (_, _, _, _, _) => sprite,
                () => { });

            Color preservedColor = texture.GetPixel(1, 15);
            editing.PaintSubPixel(cell, 0, 0, 16, Color.red);

            MapTilePixelData pixels = mapData.GetPixelData(0, 0, MapEditorLayerType.Ground);
            Require(pixels != null, "Painting over a PNG tile did not create editable pixel data.");
            Require(pixels.GetPixel(0, 0) == Color.red, "The requested pixel was not painted.");
            Require(pixels.GetPixel(1, 0) == preservedColor, "An untouched PNG pixel was reset while painting.");
            Require(mapData.GetImageIndex(0, 0, MapEditorLayerType.Ground) == -1, "The edited tile still references the source PNG.");

            editing.Undo();
            Require(mapData.GetTile(0, 0, MapEditorLayerType.Ground) == MapEditorManager.CustomImageTileId, "Undo did not restore the PNG tile type.");
            Require(mapData.GetImagePath(0, 0, MapEditorLayerType.Ground) == "smoke.png", "Undo did not restore the PNG path.");
            Require(mapData.GetImageIndex(0, 0, MapEditorLayerType.Ground) == 0, "Undo did not restore the PNG tile index.");
            Require(mapData.GetPixelData(0, 0, MapEditorLayerType.Ground) == null, "Undo left baked pixel data behind.");

            Debug.Log("PNG overwrite smoke test passed.");
        }
        finally
        {
            MapEditorObjectUtility.DestroyObject(cellObject);
            MapEditorObjectUtility.DestroyObject(sprite);
            MapEditorObjectUtility.DestroyObject(texture);
        }
    }

    private static MapData CreateSmokeTestMap(string sourceTilesetPath)
    {
        MapData mapData = new MapData(4, 4);

        for (int y = 0; y < mapData.height; y++)
        {
            for (int x = 0; x < mapData.width; x++)
            {
                Color color = ((x + y) % 2 == 0)
                    ? new Color(0.25f, 0.55f, 0.85f, 1f)
                    : new Color(0.35f, 0.65f, 0.35f, 1f);
                mapData.SetTileOnLayer(x, y, MapEditorLayerType.Ground, MapEditorManager.CustomColorTileId, color, string.Empty, -1, 0, false, false);
            }
        }

        mapData.SetTileOnLayer(0, 0, MapEditorLayerType.WallCollision, MapEditorManager.WallTileId, Color.black, string.Empty, -1, 0, false, false);
        int subTileIndex = MapEditorPngTilesetService.EncodeSubTileIndex(1, 4, 4, 8);
        mapData.SetTileOnLayer(0, 1, MapEditorLayerType.Ground, MapEditorManager.CustomImageTileId, Color.white, sourceTilesetPath, subTileIndex, 90, false, false);
        mapData.SetTileOnLayer(3, 3, MapEditorLayerType.Object, MapEditorManager.CustomColorTileId, Color.yellow, string.Empty, -1, 0, false, false);
        MapTilePixelData pixels = MapTilePixelData.CreateFilled(4, Color.yellow);
        pixels.SetPixel(0, 0, Color.red);
        mapData.SetPixelDataOnLayer(3, 3, MapEditorLayerType.Object, pixels);
        mapData.SetTileOnLayer(1, 2, MapEditorLayerType.Zone, MapEditorManager.CustomColorTileId, new Color(1f, 0.6f, 0.1f, 0.45f), string.Empty, -1, 0, false, false);
        mapData.SetTileOnLayer(2, 2, MapEditorLayerType.Zone, MapEditorManager.CustomColorTileId, new Color(1f, 0.6f, 0.1f, 0.45f), string.Empty, -1, 0, false, false);

        return mapData;
    }

    private static string CreateSmokeTestTileset(string root)
    {
        string path = Path.Combine(root, "source_tileset.png");
        Texture2D texture = new Texture2D(32, 16, TextureFormat.RGBA32, false);

        for (int y = 0; y < texture.height; y++)
        {
            for (int x = 0; x < texture.width; x++)
            {
                texture.SetPixel(x, y, x < 16 ? Color.green : Color.blue);
            }
        }

        texture.Apply();
        File.WriteAllBytes(path, texture.EncodeToPNG());
        MapEditorObjectUtility.DestroyObject(texture);
        return path;
    }

    private static Texture2D CreatePngOverwriteSourceTexture()
    {
        Texture2D texture = new Texture2D(16, 16, TextureFormat.RGBA32, false)
        {
            filterMode = FilterMode.Point
        };

        for (int y = 0; y < texture.height; y++)
        {
            for (int x = 0; x < texture.width; x++)
            {
                texture.SetPixel(x, y, new Color(x / 15f, y / 15f, 0.25f, 1f));
            }
        }

        texture.Apply();
        return texture;
    }

    private static bool ValidateMapJson(string mapPath)
    {
        if (!File.Exists(mapPath))
        {
            Debug.LogError("MapEditor export smoke test missing map.json: " + mapPath);
            return false;
        }

        string json = File.ReadAllText(mapPath);
        PixelChromaMapExportData map = JsonUtility.FromJson<PixelChromaMapExportData>(json);
        bool contractValid = map != null
            && map.format == PixelChromaExportContract.Format
            && map.version == PixelChromaExportContract.Version
            && map.cellSize == PixelChromaExportContract.TilePixelSize
            && map.tilesets != null
            && map.tilesets.Count == 0
            && HasBakedPngTile(map)
            && HasPixelTile(map)
            && HasWallCollisionTile(map);

        if (!contractValid)
        {
            Debug.LogError("MapEditor export smoke test found an invalid PixelChroma v3 game contract.");
            return false;
        }

        return RequireJsonText(json, "map.json", "\"format\": \"PixelChromaMap\"")
            && RequireJsonText(json, "map.json", "\"loaderStrategy\": \"RuntimeTilemapLoader\"")
            && RequireJsonText(json, "map.json", "\"layerBindings\"")
            && RequireJsonText(json, "map.json", "\"spawnPoints\"")
            && RequireJsonText(json, "map.json", "\"zones\"");
    }

    private static bool HasBakedPngTile(PixelChromaMapExportData map)
    {
        foreach (PixelChromaMapLayerExportData layer in map.layers)
        {
            foreach (PixelChromaTileExportData tile in layer.tiles)
            {
                if (tile.x == 0
                    && tile.y == 1
                    && tile.kind == PixelChromaExportContract.PixelTileKind
                    && tile.tileId == -1
                    && tile.pixelResolution == PixelChromaExportContract.TilePixelSize
                    && tile.pixelHexes != null
                    && tile.pixelHexes.Length == 256
                    && tile.rotation == 1)
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static bool HasPixelTile(PixelChromaMapExportData map)
    {
        foreach (PixelChromaMapLayerExportData layer in map.layers)
        {
            foreach (PixelChromaTileExportData tile in layer.tiles)
            {
                if (tile.x == 3
                    && tile.y == 3
                    && tile.kind == PixelChromaExportContract.PixelTileKind
                    && tile.pixelResolution == 4
                    && tile.pixelHexes != null
                    && tile.pixelHexes.Length == 16)
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static bool HasWallCollisionTile(PixelChromaMapExportData map)
    {
        foreach (PixelChromaMapLayerExportData layer in map.layers)
        {
            if (layer.kind != "collision")
            {
                continue;
            }

            foreach (PixelChromaTileExportData tile in layer.tiles)
            {
                if (tile.x == 0 && tile.y == 0)
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static void ValidateValidationReport(PixelChromaMapValidationReport validation)
    {
        Require(validation.passedChecks.Count > 0, "Validation did not include passed checks.");
        Require(
            validation.passedChecks.Exists(message => message.StartsWith("맵 크기:")),
            "Validation result did not contain readable Korean text.");
        Require(validation.wallTileCount == 1, "Validation did not count the Wall collision layer.");
        Require(validation.spawnPointCount == 2, "Validation did not count all spawn points.");
    }

    private static void ValidateLayerRoundTrip(MapData source)
    {
        MapSaveData saveData = source.ToSaveData();
        MapData loaded = MapData.FromSaveData(saveData);

        Require(
            loaded.GetTile(0, 0, MapEditorLayerType.Ground) == MapEditorManager.CustomColorTileId,
            "Loading removed the visual Ground tile below a Wall property.");
        Require(
            loaded.GetTile(0, 0, MapEditorLayerType.WallCollision) == MapEditorManager.WallTileId,
            "Loading removed the Wall collision property.");
        Require(
            loaded.GetTile(3, 3, MapEditorLayerType.Object) == MapEditorManager.CustomColorTileId,
            "Loading removed the Object layer.");

        MapTilePixelData loadedPixels = loaded.GetPixelData(3, 3, MapEditorLayerType.Object);
        Require(
            loadedPixels != null && loadedPixels.resolution == 4 && loadedPixels.GetPixel(0, 0) == Color.red,
            "Loading changed layered pixel data.");
    }

    private static bool ValidateWorkshopPackage(string packagePath)
    {
        string manifestPath = Path.Combine(packagePath, "manifest.json");
        string mapPath = Path.Combine(packagePath, "map.json");
        string previewPath = Path.Combine(packagePath, "preview.png");
        string reportPath = Path.Combine(packagePath, "package_report.json");
        string steamUploadPath = Path.Combine(packagePath, "steam_upload.json");
        string readmePath = Path.Combine(packagePath, "README.txt");
        string tilesetPath = Path.Combine(packagePath, "tilesets");

        bool valid = RequireFile(manifestPath)
            & RequireFile(mapPath)
            & RequireFile(previewPath)
            & RequireFile(reportPath)
            & RequireFile(steamUploadPath)
            & RequireFile(readmePath)
            & RequireDirectory(tilesetPath);

        if (!valid)
        {
            return false;
        }

        Texture2D preview = new Texture2D(2, 2, TextureFormat.RGBA32, false);
        try
        {
            Require(preview.LoadImage(File.ReadAllBytes(previewPath)), "Workshop preview PNG could not be decoded.");
            Require(preview.width == 64 && preview.height == 64, "Workshop preview size does not match the 4x4 map at 16 pixels per tile.");
        }
        finally
        {
            MapEditorObjectUtility.DestroyObject(preview);
        }

        string reportJson = File.ReadAllText(reportPath);
        return RequireJsonText(reportJson, "package_report.json", "\"isValid\": true")
            && RequireJsonText(reportJson, "package_report.json", "\"manifestExists\": true")
            && RequireJsonText(reportJson, "package_report.json", "\"mapFileExists\": true")
            && RequireJsonText(reportJson, "package_report.json", "\"previewExists\": true");
    }

    private static bool RequireFile(string path)
    {
        if (File.Exists(path) && new FileInfo(path).Length > 0)
        {
            return true;
        }

        Debug.LogError("MapEditor export smoke test missing required file: " + path);
        return false;
    }

    private static bool RequireDirectory(string path)
    {
        if (Directory.Exists(path))
        {
            return true;
        }

        Debug.LogError("MapEditor export smoke test missing required folder: " + path);
        return false;
    }

    private static bool RequireJsonText(string json, string fileName, string expectedText)
    {
        if (!string.IsNullOrEmpty(json) && json.Contains(expectedText))
        {
            return true;
        }

        Debug.LogError("MapEditor export smoke test missing expected text in " + fileName + ": " + expectedText);
        return false;
    }

    private static void Require(bool condition, string message)
    {
        if (!condition)
        {
            throw new InvalidOperationException(message);
        }
    }
}
