using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

public static class MapEditorExportSmokeTest
{
    [MenuItem("Tools/MapEditor/Run Export Smoke Test")]
    public static void RunFromMenu()
    {
        Run();
    }

    public static void RunBatchMode()
    {
        if (!Run())
        {
            throw new InvalidOperationException("MapEditor export smoke test failed.");
        }
    }

    public static bool Run()
    {
        string root = Path.Combine(Path.GetTempPath(), "MapEditorExportSmokeTest_" + DateTime.Now.ToString("yyyyMMdd_HHmmss"));
        Directory.CreateDirectory(root);

        string sourceTilesetPath = CreateSmokeTestTileset(root);
        MapData mapData = CreateSmokeTestMap(sourceTilesetPath);
        MapEditorSpawnPointData[] spawnPoints =
        {
            new MapEditorSpawnPointData("SpawnPoint_1", 1, 1, "Any"),
            new MapEditorSpawnPointData("SpawnPoint_2", 2, 1, "Any")
        };

        PixelChromaMapValidationReport validation = MapEditorPixelChromaValidationService.Validate(mapData, 1, 1, spawnPoints);

        if (!validation.isValid)
        {
            MapEditorPixelChromaValidationService.Log(validation);
            Debug.LogError("MapEditor export smoke test failed during validation.");
            return false;
        }

        ValidateValidationReport(validation);
        ValidateLayerRoundTrip(mapData);
        ValidateLayerIsolation();
        ValidateLayerSettingsRoundTrip();
        ValidateBrushGeometry();
        ValidateOverlappingPixelPaint();
        ValidateConnectedSelectionMove();
        ValidateFullImageTile(root);

        string mapPath = Path.Combine(root, "map.json");
        MapEditorPixelChromaExportService mapExport = new MapEditorPixelChromaExportService();

        if (!mapExport.Export(mapData, mapPath, "smoke_test", 16, 1, 1, spawnPoints))
        {
            Debug.LogError("MapEditor export smoke test failed while writing map.json.");
            return false;
        }

        if (!ValidateMapJson(mapPath))
        {
            return false;
        }

        string packagePath = Path.Combine(root, "workshop_package");
        MapEditorWorkshopExportService workshopExport = new MapEditorWorkshopExportService((_, _) => null);

        if (!workshopExport.Export(
            mapData,
            packagePath,
            "smoke_test",
            "Smoke Test",
            "MapEditor",
            "Generated by MapEditor export smoke test.",
            "1.0.0",
            "Private",
            "Map,SmokeTest",
            1,
            1,
            spawnPoints,
            16,
            false))
        {
            Debug.LogError("MapEditor export smoke test failed while writing workshop package.");
            return false;
        }

        if (!ValidateWorkshopPackage(packagePath))
        {
            return false;
        }

        Debug.Log("MapEditor export smoke test passed: " + root);
        return true;
    }

    [MenuItem("Tools/MapEditor/Run PNG Overwrite Smoke Test")]
    public static void RunPngOverwriteTest()
    {
        Texture2D texture = null;
        Sprite sprite = null;
        GameObject cellObject = null;

        try
        {
            texture = CreatePngOverwriteSourceTexture();
            sprite = Sprite.Create(texture, new Rect(0, 0, 16, 16), new Vector2(0.5f, 0.5f), 16f);
            cellObject = new GameObject("PngOverwriteSmokeCell", typeof(RectTransform), typeof(Image));
            GridCell cell = cellObject.AddComponent<GridCell>();

            MapData mapData = new MapData(1, 1);
            mapData.SetTileOnLayer(0, 0, MapEditorLayerType.Ground, MapEditorManager.CustomImageTileId, Color.white, "smoke.png", 0, 0, false, false);

            Dictionary<Vector2Int, GridCell> cells = new Dictionary<Vector2Int, GridCell>();
            MapEditorMapEditingService editing = new MapEditorMapEditingService(
                () => mapData,
                () => MapEditorLayerType.Ground,
                _ => true,
                cells,
                (_, _, _, _, _) => sprite,
                () => { });

            Color preservedColor = texture.GetPixel(1, 15);
            editing.PaintSubPixel(cell, 0, 0, 16, Color.red);

            MapTilePixelData pixels = mapData.GetPixelData(0, 0, MapEditorLayerType.Ground);
            Require(pixels != null, "Painting over a PNG tile did not create editable pixel data.");
            Require(pixels.GetPixel(0, 0) == Color.red, "The requested pixel was not painted.");
            Require(pixels.GetPixel(1, 0) == preservedColor, "An untouched PNG pixel was reset while painting.");
            Require(mapData.GetImageIndex(0, 0, MapEditorLayerType.Ground) == -1, "The edited tile still references the source PNG.");

            editing.Undo();
            Require(mapData.GetTile(0, 0, MapEditorLayerType.Ground) == MapEditorManager.CustomImageTileId, "Undo did not restore the PNG tile type.");
            Require(mapData.GetImagePath(0, 0, MapEditorLayerType.Ground) == "smoke.png", "Undo did not restore the PNG path.");
            Require(mapData.GetImageIndex(0, 0, MapEditorLayerType.Ground) == 0, "Undo did not restore the PNG tile index.");
            Require(mapData.GetPixelData(0, 0, MapEditorLayerType.Ground) == null, "Undo left baked pixel data behind.");

            Debug.Log("PNG overwrite smoke test passed.");
        }
        finally
        {
            MapEditorObjectUtility.DestroyObject(cellObject);
            MapEditorObjectUtility.DestroyObject(sprite);
            MapEditorObjectUtility.DestroyObject(texture);
        }
    }

    private static MapData CreateSmokeTestMap(string sourceTilesetPath)
    {
        MapData mapData = new MapData(4, 4);

        for (int y = 0; y < mapData.height; y++)
        {
            for (int x = 0; x < mapData.width; x++)
            {
                Color color = ((x + y) % 2 == 0)
                    ? new Color(0.25f, 0.55f, 0.85f, 1f)
                    : new Color(0.35f, 0.65f, 0.35f, 1f);
                mapData.SetTileOnLayer(x, y, MapEditorLayerType.Ground, MapEditorManager.CustomColorTileId, color, string.Empty, -1, 0, false, false);
            }
        }

        mapData.SetTileOnLayer(0, 0, MapEditorLayerType.WallCollision, MapEditorManager.WallTileId, Color.black, string.Empty, -1, 0, false, false);
        int subTileIndex = MapEditorPngTilesetService.EncodeSubTileIndex(1, 4, 4, 8);
        mapData.SetTileOnLayer(0, 1, MapEditorLayerType.Ground, MapEditorManager.CustomImageTileId, Color.white, sourceTilesetPath, subTileIndex, 90, false, false);
        mapData.SetTileOnLayer(3, 3, MapEditorLayerType.Object, MapEditorManager.CustomColorTileId, Color.yellow, string.Empty, -1, 0, false, false);
        MapTilePixelData pixels = MapTilePixelData.CreateFilled(4, Color.yellow);
        pixels.SetPixel(0, 0, Color.red);
        mapData.SetPixelDataOnLayer(3, 3, MapEditorLayerType.Object, pixels);
        MapTilePixelData extraPixels = MapTilePixelData.CreateFilled(16, Color.clear);
        extraPixels.SetPixel(1, 1, Color.blue);
        mapData.SetTileOnLayer(3, 3, MapEditorLayerType.ObjectExtra, MapEditorManager.CustomColorTileId, Color.clear, string.Empty, -1, 0, false, false);
        mapData.SetPixelDataOnLayer(3, 3, MapEditorLayerType.ObjectExtra, extraPixels);
        mapData.SetTileOnLayer(1, 2, MapEditorLayerType.Zone, MapEditorManager.CustomColorTileId, new Color(1f, 0.6f, 0.1f, 0.45f), string.Empty, -1, 0, false, false);
        mapData.SetTileOnLayer(2, 2, MapEditorLayerType.Zone, MapEditorManager.CustomColorTileId, new Color(1f, 0.6f, 0.1f, 0.45f), string.Empty, -1, 0, false, false);

        return mapData;
    }

    private static string CreateSmokeTestTileset(string root)
    {
        string path = Path.Combine(root, "source_tileset.png");
        Texture2D texture = new Texture2D(32, 16, TextureFormat.RGBA32, false);

        for (int y = 0; y < texture.height; y++)
        {
            for (int x = 0; x < texture.width; x++)
            {
                texture.SetPixel(x, y, x < 16 ? Color.green : Color.blue);
            }
        }

        texture.Apply();
        File.WriteAllBytes(path, texture.EncodeToPNG());
        MapEditorObjectUtility.DestroyObject(texture);
        return path;
    }

    private static Texture2D CreatePngOverwriteSourceTexture()
    {
        Texture2D texture = new Texture2D(16, 16, TextureFormat.RGBA32, false)
        {
            filterMode = FilterMode.Point
        };

        for (int y = 0; y < texture.height; y++)
        {
            for (int x = 0; x < texture.width; x++)
            {
                texture.SetPixel(x, y, new Color(x / 15f, y / 15f, 0.25f, 1f));
            }
        }

        texture.Apply();
        return texture;
    }

    private static bool ValidateMapJson(string mapPath)
    {
        if (!File.Exists(mapPath))
        {
            Debug.LogError("MapEditor export smoke test missing map.json: " + mapPath);
            return false;
        }

        string json = File.ReadAllText(mapPath);
        PixelChromaMapExportData map = JsonUtility.FromJson<PixelChromaMapExportData>(json);
        bool contractValid = map != null
            && map.format == PixelChromaExportContract.Format
            && map.version == PixelChromaExportContract.Version
            && map.cellSize == PixelChromaExportContract.TilePixelSize
            && map.tilesets != null
            && map.tilesets.Count == 0
            && HasBakedPngTile(map)
            && HasPixelTile(map)
            && HasWallCollisionTile(map);

        if (!contractValid)
        {
            Debug.LogError("MapEditor export smoke test found an invalid PixelChroma v3 game contract.");
            return false;
        }

        return RequireJsonText(json, "map.json", "\"format\": \"PixelChromaMap\"")
            && RequireJsonText(json, "map.json", "\"loaderStrategy\": \"RuntimeTilemapLoader\"")
            && RequireJsonText(json, "map.json", "\"layerBindings\"")
            && RequireJsonText(json, "map.json", "\"spawnPoints\"")
            && RequireJsonText(json, "map.json", "\"zones\"")
            && HasNoDuplicateLayerCoordinates(map);
    }

    private static bool HasNoDuplicateLayerCoordinates(PixelChromaMapExportData map)
    {
        foreach (PixelChromaMapLayerExportData layer in map.layers)
        {
            HashSet<Vector2Int> coordinates = new HashSet<Vector2Int>();

            foreach (PixelChromaTileExportData tile in layer.tiles)
            {
                if (!coordinates.Add(new Vector2Int(tile.x, tile.y)))
                {
                    Debug.LogError("Exported layer contains duplicate coordinates at (" + tile.x + ", " + tile.y + ").");
                    return false;
                }
            }
        }

        return true;
    }

    private static bool HasBakedPngTile(PixelChromaMapExportData map)
    {
        foreach (PixelChromaMapLayerExportData layer in map.layers)
        {
            foreach (PixelChromaTileExportData tile in layer.tiles)
            {
                if (tile.x == 0
                    && tile.y == 1
                    && tile.kind == PixelChromaExportContract.PixelTileKind
                    && tile.tileId == -1
                    && tile.pixelResolution == PixelChromaExportContract.TilePixelSize
                    && tile.pixelHexes != null
                    && tile.pixelHexes.Length == 256
                    && tile.rotation == 1)
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static bool HasPixelTile(PixelChromaMapExportData map)
    {
        foreach (PixelChromaMapLayerExportData layer in map.layers)
        {
            foreach (PixelChromaTileExportData tile in layer.tiles)
            {
                if (tile.x == 3
                    && tile.y == 3
                    && tile.kind == PixelChromaExportContract.PixelTileKind
                    && tile.pixelResolution == PixelChromaExportContract.TilePixelSize
                    && tile.pixelHexes != null
                    && tile.pixelHexes.Length == 256)
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static bool HasWallCollisionTile(PixelChromaMapExportData map)
    {
        foreach (PixelChromaMapLayerExportData layer in map.layers)
        {
            if (layer.kind != "collision")
            {
                continue;
            }

            foreach (PixelChromaTileExportData tile in layer.tiles)
            {
                if (tile.x == 0 && tile.y == 0)
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static void ValidateValidationReport(PixelChromaMapValidationReport validation)
    {
        Require(validation.passedChecks.Count > 0, "Validation did not include passed checks.");
        Require(
            validation.passedChecks.Exists(message => message.StartsWith("맵 크기:")),
            "Validation result did not contain readable Korean text.");
        Require(validation.wallTileCount == 1, "Validation did not count the Wall collision layer.");
        Require(validation.spawnPointCount == 2, "Validation did not count all spawn points.");
    }

    private static void ValidateLayerRoundTrip(MapData source)
    {
        MapSaveData saveData = source.ToSaveData();
        MapData loaded = MapData.FromSaveData(saveData);

        Require(
            loaded.GetTile(0, 0, MapEditorLayerType.Ground) == MapEditorManager.CustomColorTileId,
            "Loading removed the visual Ground tile below a Wall property.");
        Require(
            loaded.GetTile(0, 0, MapEditorLayerType.WallCollision) == MapEditorManager.WallTileId,
            "Loading removed the Wall collision property.");
        Require(
            loaded.GetTile(3, 3, MapEditorLayerType.Object) == MapEditorManager.CustomColorTileId,
            "Loading removed the Object layer.");

        MapTilePixelData loadedPixels = loaded.GetPixelData(3, 3, MapEditorLayerType.Object);
        Require(
            loadedPixels != null && loadedPixels.resolution == 4 && loadedPixels.GetPixel(0, 0) == Color.red,
            "Loading changed layered pixel data.");
        Require(
            loaded.GetPixelData(3, 3, MapEditorLayerType.ObjectExtra)?.GetPixel(1, 1) == Color.blue,
            "Loading removed the optional Object layer.");
    }

    private static void ValidateLayerIsolation()
    {
        MapData source = new MapData(2, 2);
        Color groundColor = new Color(0.2f, 0.6f, 0.3f, 1f);
        source.SetTileOnLayer(
            0, 0, MapEditorLayerType.Ground, MapEditorManager.CustomColorTileId,
            groundColor, string.Empty, -1, 0, false, false);

        MapTilePixelData objectPixels = MapTilePixelData.CreateFilled(16, Color.clear);
        objectPixels.SetPixel(3, 4, Color.red);
        source.SetTileOnLayer(
            0, 0, MapEditorLayerType.Object, MapEditorManager.CustomColorTileId,
            Color.white, string.Empty, -1, 0, false, false);
        source.SetPixelDataOnLayer(0, 0, MapEditorLayerType.Object, objectPixels);

        MapData loaded = MapData.FromSaveData(source.ToSaveData());
        Require(
            loaded.GetTile(0, 0, MapEditorLayerType.Ground) == MapEditorManager.CustomColorTileId
                && loaded.GetColor(0, 0, MapEditorLayerType.Ground) == groundColor,
            "Object painting or save/load changed the Ground layer.");
        Require(
            loaded.GetPixelData(0, 0, MapEditorLayerType.Object)?.GetPixel(3, 4) == Color.red,
            "Save/load removed transparent Object-layer pixel data.");

        loaded.ClearLayer(MapEditorLayerType.Object);
        Require(
            loaded.GetTile(0, 0, MapEditorLayerType.Object) == -1,
            "Clearing the Object layer left Object data behind.");
        Require(
            loaded.GetTile(0, 0, MapEditorLayerType.Ground) == MapEditorManager.CustomColorTileId
                && loaded.GetColor(0, 0, MapEditorLayerType.Ground) == groundColor,
            "Clearing the Object layer also cleared the Ground layer.");
    }

    private static void ValidateLayerSettingsRoundTrip()
    {
        MapSaveData source = new MapSaveData(2, 2)
        {
            layerSettings = new[]
            {
                new MapEditorLayerSetting(MapEditorLayerType.Ground, "Floor", true),
                new MapEditorLayerSetting(MapEditorLayerType.Object, "Decoration", false),
                new MapEditorLayerSetting(MapEditorLayerType.WallVisual, "Wall", true),
                new MapEditorLayerSetting(MapEditorLayerType.ObjectExtra, "Props", true, true)
            }
        };

        MapSaveData loaded = JsonUtility.FromJson<MapSaveData>(JsonUtility.ToJson(source));

        Require(loaded.formatVersion == 5, "Layer settings did not use map format version 5.");
        Require(loaded.layerSettings != null && loaded.layerSettings.Length == 4, "Layer settings were not serialized.");
        Require(loaded.layerSettings[0].displayName == "Floor", "A custom layer name was not preserved.");
        Require(!loaded.layerSettings[1].visible, "A hidden layer was restored as visible.");
        Require(loaded.layerSettings[3].enabled, "An enabled optional layer was restored as disabled.");
    }

    private static void ValidateBrushGeometry()
    {
        List<Vector2Int> line = new List<Vector2Int>();
        MapEditorBrushGeometry.RasterizeLine(new Vector2Int(1, 2), new Vector2Int(9, 6), line.Add);

        Require(line.Count == 9, "Brush interpolation did not cover the longest line axis.");
        Require(line[0] == new Vector2Int(1, 2) && line[line.Count - 1] == new Vector2Int(9, 6),
            "Brush interpolation changed a stroke endpoint.");

        for (int i = 1; i < line.Count; i++)
        {
            Vector2Int delta = line[i] - line[i - 1];
            Require(Mathf.Abs(delta.x) <= 1 && Mathf.Abs(delta.y) <= 1,
                "Brush interpolation left a gap between stroke samples.");
        }

        const int sourceWidth = 2;
        const int sourceHeight = 3;
        Vector2Int rotatedSize = MapEditorBrushGeometry.GetRotatedSize(sourceWidth, sourceHeight, 90);
        Require(rotatedSize == new Vector2Int(3, 2), "A 90-degree brush rotation did not swap its dimensions.");

        HashSet<Vector2Int> visitedSourceTiles = new HashSet<Vector2Int>();

        for (int y = 0; y < rotatedSize.y; y++)
        {
            for (int x = 0; x < rotatedSize.x; x++)
            {
                Vector2Int source = MapEditorBrushGeometry.MapOutputToSource(
                    x, y, sourceWidth, sourceHeight, 90, false, false);
                Require(source.x >= 0 && source.x < sourceWidth && source.y >= 0 && source.y < sourceHeight,
                    "A rotated brush tile mapped outside its source selection.");
                visitedSourceTiles.Add(source);
            }
        }

        Require(visitedSourceTiles.Count == sourceWidth * sourceHeight,
            "A rotated multi-tile brush duplicated or omitted source tiles.");
    }

    private static void ValidateOverlappingPixelPaint()
    {
        GameObject cellObject = new GameObject("OverlappingPixelPaintCell", typeof(RectTransform), typeof(Image));

        try
        {
            GridCell cell = cellObject.AddComponent<GridCell>();
            MapData mapData = new MapData(1, 1);
            MapEditorMapEditingService editing = new MapEditorMapEditingService(
                () => mapData,
                () => MapEditorLayerType.Ground,
                _ => true,
                new Dictionary<Vector2Int, GridCell>(),
                (_, _, _, _, _) => null,
                () => { });

            editing.PaintSubPixelArea(cell, 3, 5, 16, 2, Color.red);
            editing.PaintSubPixelArea(cell, 3, 5, 16, 2, Color.blue);

            MapTilePixelData pixels = mapData.GetPixelData(0, 0, MapEditorLayerType.Ground);
            Require(pixels != null && pixels.GetPixel(3, 5) == Color.blue && pixels.GetPixel(4, 6) == Color.blue,
                "A later pixel brush stroke did not overwrite an earlier stroke.");
        }
        finally
        {
            UnityEngine.Object.DestroyImmediate(cellObject);
        }
    }

    private static void ValidateConnectedSelectionMove()
    {
        MapData mapData = new MapData(6, 5);
        MapEditorLayerType layer = MapEditorLayerType.Object;
        mapData.SetTileOnLayer(1, 1, layer, MapEditorManager.CustomColorTileId, Color.red, string.Empty, -1, 0, false, false);
        mapData.SetTileOnLayer(2, 1, layer, MapEditorManager.CustomColorTileId, Color.green, string.Empty, -1, 0, false, false);
        mapData.SetTileOnLayer(1, 2, layer, MapEditorManager.CustomColorTileId, Color.blue, string.Empty, -1, 0, false, false);
        mapData.SetTileOnLayer(5, 4, layer, MapEditorManager.CustomColorTileId, Color.yellow, string.Empty, -1, 0, false, false);
        mapData.SetTileOnLayer(1, 1, MapEditorLayerType.Ground, MapEditorManager.CustomColorTileId, Color.gray, string.Empty, -1, 0, false, false);

        MapTilePixelData pixels = MapTilePixelData.CreateFilled(16, Color.blue);
        pixels.SetPixel(3, 4, Color.magenta);
        mapData.SetPixelDataOnLayer(1, 2, layer, pixels);

        MapEditorMapEditingService editing = new MapEditorMapEditingService(
            () => mapData,
            () => layer,
            _ => true,
            new Dictionary<Vector2Int, GridCell>(),
            (_, _, _, _, _) => null,
            () => { });

        HashSet<Vector2Int> connected = new HashSet<Vector2Int>
        {
            new Vector2Int(1, 1),
            new Vector2Int(2, 1),
            new Vector2Int(1, 2)
        };

        MapEditorSelectionClipboardService selection = new MapEditorSelectionClipboardService(
            editing,
            () => mapData,
            () => null,
            () => layer,
            (_, _, _) => { },
            () => { },
            () => { },
            () => { },
            () => { });
        selection.SelectConnectedAt(new Vector2Int(1, 1));
        Require(selection.SelectionPreviewCells.Count == connected.Count, "Connected selection included a disconnected tile or missed a neighbor.");
        Require(selection.MoveSelection(Vector2Int.right), "Connected selection could not move into empty cells.");
        Require(mapData.GetTile(1, 1, layer) == -1 && mapData.GetTile(1, 2, layer) == -1, "Moving left source tiles behind.");
        Require(mapData.GetColor(2, 1, layer) == Color.red && mapData.GetColor(3, 1, layer) == Color.green, "Overlapping move changed tile order or colors.");
        Require(mapData.GetPixelData(2, 2, layer)?.GetPixel(3, 4) == Color.magenta, "Moving lost custom pixel data.");
        Require(mapData.GetTile(5, 4, layer) != -1, "Moving changed a disconnected tile.");
        Require(mapData.GetTile(1, 1, MapEditorLayerType.Ground) != -1, "Moving Object tiles changed the Ground layer.");

        editing.Undo();
        Require(mapData.GetColor(1, 1, layer) == Color.red && mapData.GetColor(2, 1, layer) == Color.green, "Undo did not restore connected tiles.");
        Require(mapData.GetPixelData(1, 2, layer)?.GetPixel(3, 4) == Color.magenta, "Undo did not restore moved pixel data.");

        mapData.SetTileOnLayer(3, 1, layer, MapEditorManager.CustomColorTileId, Color.black, string.Empty, -1, 0, false, false);
        Require(!editing.MoveConnectedCells(connected, layer, Vector2Int.right), "Connected selection overwrote an occupied destination.");
        Require(mapData.GetColor(3, 1, layer) == Color.black, "Blocked move changed the destination tile.");
    }

    private static void ValidateFullImageTile(string root)
    {
        string path = Path.Combine(root, "created_tile.png");
        Texture2D texture = new Texture2D(16, 16, TextureFormat.RGBA32, false);

        for (int y = 0; y < texture.height; y++)
        {
            for (int x = 0; x < texture.width; x++)
            {
                texture.SetPixel(x, y, x == 15 && y == 15 ? Color.red : Color.clear);
            }
        }

        texture.Apply();
        File.WriteAllBytes(path, texture.EncodeToPNG());
        MapEditorObjectUtility.DestroyObject(texture);

        MapEditorPngTilesetService service = new MapEditorPngTilesetService();
        Sprite sprite = service.GetTileSprite(path, MapEditorPngTilesetService.FullImageTileIndex);

        Require(sprite != null, "The created tile could not be loaded as a brush.");
        Require(Mathf.RoundToInt(sprite.rect.width) == 16 && Mathf.RoundToInt(sprite.rect.height) == 16, "The created tile was sliced instead of using the full 16x16 image.");
        Require(sprite.texture.GetPixel(15, 15) == Color.red, "The created tile changed pixel data while loading.");
    }

    private static bool ValidateWorkshopPackage(string packagePath)
    {
        string manifestPath = Path.Combine(packagePath, "manifest.json");
        string mapPath = Path.Combine(packagePath, "map.json");
        string previewPath = Path.Combine(packagePath, "preview.png");
        string reportPath = Path.Combine(packagePath, "package_report.json");
        string steamUploadPath = Path.Combine(packagePath, "steam_upload.json");
        string readmePath = Path.Combine(packagePath, "README.txt");
        string tilesetPath = Path.Combine(packagePath, "tilesets");

        bool valid = RequireFile(manifestPath)
            & RequireFile(mapPath)
            & RequireFile(previewPath)
            & RequireFile(reportPath)
            & RequireFile(steamUploadPath)
            & RequireFile(readmePath)
            & RequireDirectory(tilesetPath);

        if (!valid)
        {
            return false;
        }

        Texture2D preview = new Texture2D(2, 2, TextureFormat.RGBA32, false);
        try
        {
            Require(preview.LoadImage(File.ReadAllBytes(previewPath)), "Workshop preview PNG could not be decoded.");
            Require(preview.width == 64 && preview.height == 64, "Workshop preview size does not match the 4x4 map at 16 pixels per tile.");
        }
        finally
        {
            MapEditorObjectUtility.DestroyObject(preview);
        }

        string reportJson = File.ReadAllText(reportPath);
        return RequireJsonText(reportJson, "package_report.json", "\"isValid\": true")
            && RequireJsonText(reportJson, "package_report.json", "\"manifestExists\": true")
            && RequireJsonText(reportJson, "package_report.json", "\"mapFileExists\": true")
            && RequireJsonText(reportJson, "package_report.json", "\"previewExists\": true");
    }

    private static bool RequireFile(string path)
    {
        if (File.Exists(path) && new FileInfo(path).Length > 0)
        {
            return true;
        }

        Debug.LogError("MapEditor export smoke test missing required file: " + path);
        return false;
    }

    private static bool RequireDirectory(string path)
    {
        if (Directory.Exists(path))
        {
            return true;
        }

        Debug.LogError("MapEditor export smoke test missing required folder: " + path);
        return false;
    }

    private static bool RequireJsonText(string json, string fileName, string expectedText)
    {
        if (!string.IsNullOrEmpty(json) && json.Contains(expectedText))
        {
            return true;
        }

        Debug.LogError("MapEditor export smoke test missing expected text in " + fileName + ": " + expectedText);
        return false;
    }

    private static void Require(bool condition, string message)
    {
        if (!condition)
        {
            throw new InvalidOperationException(message);
        }
    }
}
